services:
  backend:
    build: ./server
    container_name: flask_backend
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./client
    container_name: next_frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:5000
    depends_on:
      - backend
